### ISSUE TITLE
the problem of AMM Module

### ISSUE THREAD

**Issue by SeeU1119** [wtjiang98/PSGAN#6]
Thank you for your excellent work! 
When I read the code, I find the implementation is not same as paper says. After gamma and beta are calculated, follow the paper, we should do: Vx * gamma + beta, but the code is: Vx * (1 + gamma) * beta, why need this add operation?
Moreover, why after get gamma_s and beta_s, then do gamma_s * mask_s, beta_s * mask_s, i can not find it in the paper.   
Thanks, looking forward to your reply.

**Comment by wtjiang98** [comment]
> Thank you for your excellent work!
> When I read the code, I find the implementation is not same as paper says. After gamma and beta are calculated, follow the paper, we should do: Vx * gamma + beta, but the code is: Vx * (1 + gamma) * beta, why need this add operation?
> Moreover, why after get gamma_s and beta_s, then do gamma_s * mask_s, beta_s * mask_s, i can not find it in the paper.
> Thanks, looking forward to your reply.

1. Learning a residual may be easier for network. It is okay to change it to `Vx * gamma + beta`.
2. Do you mean the `gamma_s = gamma_s_re * mask_s_re  # (3, c, h, w)` in `net.py`? Since we apply transfer in three separate part (eye, skin, lip), we multiply the mask for each part to obtain the corresponding modulation parameters. We omit this implementation details in the paper for the limited space.

**Comment by SeeU1119** [comment]
Thanks for your quick reply, I got it!

**Comment by wtjiang98** [comment]
> Thanks for your quick reply, I got it!

You are welcome.
